### ISSUE TITLE
[Task] Artillery Test: 40 requests with cache /users/{userId}/tasks

### ISSUE THREAD

**Issue by AlexSuth** [North-Seattle-College/ad440-winter2021-thursday-repo#318]
I performed an Artillery test on the endpoint `/users/1/tasks` using the Artillery CLI.

Here is a copy of my script:
```
config:
  target: "https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api"
  phases:
    - duration: 300
      arrivalRate: 40
      name: Warm up 1 request per second

scenarios:
  - name: "simple test"
    flow:
      - get:
          url: "/users/1/tasks"
          expect:
            - statusCode: 200
```

CLI Results:
```
All virtual users finished
Summary report @ 20:30:46(-0700) 2021-03-24
    Scenarios launched:  12000
    Scenarios completed: 12000
    Requests completed:  12000
    Mean response/sec: 37.73
    Response time (msec):
        min: 116.7
        max: 58945.8
        median: 342.5
        p95: 23414.1
        p99: 32673
    Scenario counts:
        ramp test: 12000 (100%)
    Codes:
        200: 12000
```
